languageCode = "zh-cn"
languageName = "Simplified Chinese (China)"
weight = 2
title = "Aphcity ã® éƒ¨è½æ ¼"

[params]
  displayName = "ğŸ‡¨ğŸ‡³ ç®€ä½“ä¸­æ–‡"
  isoCode = "zh-CN"
  rtl = false
  dateFormat = "2006å¹´1æœˆ2æ—¥"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "My awesome website"
  copyright = "Copy, _right?_ :thinking_face:"

[author]
  name = "Aphcity"
  image = "img/avatar.5esiw34k8aw0.webp"
  headline = "åªæ˜¯ä¸€ä»‹å­¦å¾’"
  bio = "åªæ˜¯ä¸€ä»‹å­¦å¾’"
  links = [
    { email = "mailto:chalk.talisman@gmail.com" },
    # { link = "https://link-to-some-website.com/" },
    # { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
    # { apple = "https://www.apple.com" },
    # { blogger = "https://username.blogspot.com/" },
    # { bluesky = "https://bsky.app/profile/username" },
    # { codepen = "https://codepen.io/username" },
    # { dev = "https://dev.to/username" },
    # { discord = "https://discord.gg/6XefQutTvq" },
    # { dribbble = "https://dribbble.com/username" },
    # { facebook = "https://facebook.com/username" },
    # { flickr = "https://www.flickr.com/photos/username/" },
    # { foursquare = "https://foursquare.com/username" },
    # { github = "https://github.com/Aphcity" },
    # { gitlab = "https://gitlab.com/username" },
    # { google = "https://www.google.com/" },
    # { hashnode = "https://username.hashnode.dev" },
    # { instagram = "https://instagram.com/username" },
    # { keybase = "https://keybase.io/username" },
    # { kickstarter = "https://www.kickstarter.com/profile/username" },
    # { lastfm = "https://lastfm.com/user/username" },
    # { linkedin = "https://linkedin.com/in/username" },
    # { mastodon = "https://mastodon.instance/@username" },
    # { medium = "https://medium.com/username" },
    # { microsoft = "https://www.microsoft.com/" },
    # { orcid = "https://orcid.org/userid" },
    # { patreon = "https://www.patreon.com/username" },
    # { pinterest = "https://pinterest.com/username" },
    # { reddit = "https://reddit.com/user/username" },
    # { researchgate = "https://www.researchgate.net/profile/username" },
    # { slack = "https://workspace.url/team/userid" },
    # { snapchat = "https://snapchat.com/add/username" },
    # { soundcloud = "https://soundcloud.com/username" },
    # { stack-overflow = "https://stackoverflow.com/users/userid/username" },
    { steam = "https://steamcommunity.com/id/Aphcity/" },
    # { telegram = "https://t.me/username" },
    # { threads = "https://www.threads.net/@username" },
    # { tiktok = "https://tiktok.com/@username" },
    # { tumblr = "https://username.tumblr.com" },
    # { twitch = "https://twitch.tv/username" },
    # { twitter = "https://twitter.com/username" },
    # { x-twitter = "https://twitter.com/_Aphcity" },
    # { whatsapp = "https://wa.me/phone-number" },
    # { youtube = "https://youtube.com/username" },
    # { ko-fi = "https://ko-fi.com/username" },
    { bilibili = "https://space.bilibili.com/5175685"},
    # { wechat = "javascript:void(window.open('asset/img/wechat.webp', 'floating_window', 'width=400,height=400'));"},

]
